resilience4j.circuitbreaker:
    instances:
        Flightservice:           
            failureRateThreshold: 50
            slidingWindowSize: 2
            permittedNumberOfCallsInHalfOpenState: 1
            waitDurationInOpenState: 20s
            automaticTransitionFromOpenToHalfOpenEnabled: true